# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'A tag used for release'
        required: true
        type: string
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish Linux
      run: dotnet publish ./ActionsDemo/ActionsDemo.csproj --self-contained true -c Release -p:PublishSingleFile=true -o ./publish/linux --os linux
    - name: Publish Win
      run: dotnet publish ./ActionsDemo/ActionsDemo.csproj --self-contained true -c Release -p:PublishSingleFile=true -o ./publish/win --os win
    - name: Upload binaries to release
      run: gh release upload ${{ inputs.tag }} ./publish/linux/* ./publish/linux/*
